import { User, Document, ActivityLog } from '@/types'

export const mockUsers: User[] = [
  {
    id: '1',
    email: 'admin@bytes.com',
    fullName: 'Chief Minister',
    role: 'chief_minister',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    email: 'secretary@bytes.com',
    fullName: 'Secretary General',
    role: 'secretary',
    createdAt: '2024-01-16T10:00:00Z',
  },
  {
    id: '3',
    email: 'finance@bytes.com',
    fullName: 'Minister of Finance',
    role: 'finance_minister',
    createdAt: '2024-01-17T10:00:00Z',
  },
  {
    id: '4',
    email: 'member@bytes.com',
    fullName: 'Council Member',
    role: 'member',
    createdAt: '2024-01-18T10:00:00Z',
  },
  {
    id: '5',
    email: 'member2@bytes.com',
    fullName: 'Council Member 2',
    role: 'member',
    createdAt: '2024-02-01T10:00:00Z',
  },
]

export const mockDocuments: Document[] = [
  {
    id: '1',
    title: 'Freshmen Orientation Proposal',
    category: 'Proposals',
    event: 'Freshmen Orientation',
    administration: '2024-2025',
    uploadedBy: '2',
    uploadDate: '2024-03-15T14:30:00Z',
    filePath: '/mock/proposal1.pdf',
    is_archived: false,
    is_locked: false,
    fileType: 'pdf',
  },
  {
    id: '2',
    title: 'Election 2025 Budget Report',
    category: 'Budgets',
    event: 'Election 2025',
    administration: '2024-2025',
    uploadedBy: '3',
    uploadDate: '2024-04-01T09:00:00Z',
    filePath: '/mock/budget1.pdf',
    is_archived: false,
    is_locked: false,
    fileType: 'pdf',
  },
  {
    id: '3',
    title: 'Foundation Day Event Permit',
    category: 'Permits',
    event: 'Foundation Day',
    administration: '2024-2025',
    uploadedBy: '2',
    uploadDate: '2024-04-10T11:20:00Z',
    filePath: '/mock/permit1.pdf',
    is_archived: false,
    is_locked: false,
    fileType: 'pdf',
  },
  {
    id: '4',
    title: 'Q1 Financial Records',
    category: 'Financial Records',
    event: 'General',
    administration: '2024-2025',
    uploadedBy: '3',
    uploadDate: '2024-04-15T16:45:00Z',
    filePath: '/mock/financial1.pdf',
    is_archived: false,
    is_locked: false,
    fileType: 'pdf',
  },
  {
    id: '5',
    title: 'Annual Activity Report 2024',
    category: 'Reports',
    event: 'General',
    administration: '2024-2025',
    uploadedBy: '1',
    uploadDate: '2024-04-20T13:00:00Z',
    filePath: '/mock/report1.pdf',
    is_archived: true,
    is_locked: true,
    fileType: 'pdf',
  },
  {
    id: '6',
    title: 'Freshmen Orientation Budget',
    category: 'Budgets',
    event: 'Freshmen Orientation',
    administration: '2024-2025',
    uploadedBy: '3',
    uploadDate: '2024-03-20T10:15:00Z',
    filePath: '/mock/budget2.pdf',
    is_archived: false,
    is_locked: false,
    fileType: 'pdf',
  },
  {
    id: '7',
    title: 'Election Committee Proposal',
    category: 'Proposals',
    event: 'Election 2025',
    administration: '2024-2025',
    uploadedBy: '2',
    uploadDate: '2024-03-25T15:30:00Z',
    filePath: '/mock/proposal2.pdf',
    is_archived: false,
    is_locked: false,
    fileType: 'pdf',
  },
  {
    id: '8',
    title: 'Foundation Day Budget Allocation',
    category: 'Budgets',
    event: 'Foundation Day',
    administration: '2024-2025',
    uploadedBy: '3',
    uploadDate: '2024-04-05T08:45:00Z',
    filePath: '/mock/budget3.pdf',
    is_archived: false,
    is_locked: false,
    fileType: 'pdf',
  },
  {
    id: '9',
    title: 'Venue Booking Permit',
    category: 'Permits',
    event: 'Foundation Day',
    administration: '2024-2025',
    uploadedBy: '2',
    uploadDate: '2024-04-12T14:00:00Z',
    filePath: '/mock/permit2.pdf',
    is_archived: false,
    is_locked: false,
    fileType: 'pdf',
  },
  {
    id: '10',
    title: 'Q2 Expense Report',
    category: 'Reports',
    event: 'General',
    administration: '2024-2025',
    uploadedBy: '3',
    uploadDate: '2024-04-18T12:30:00Z',
    filePath: '/mock/report2.pdf',
    is_archived: false,
    is_locked: false,
    fileType: 'pdf',
  },
]

export const mockActivityLogs: ActivityLog[] = [
  {
    id: '1',
    userId: '1',
    action: 'login',
    timestamp: '2024-04-20T08:00:00Z',
  },
  {
    id: '2',
    userId: '2',
    action: 'upload',
    documentId: '1',
    timestamp: '2024-03-15T14:30:00Z',
  },
  {
    id: '3',
    userId: '3',
    action: 'upload',
    documentId: '2',
    timestamp: '2024-04-01T09:00:00Z',
  },
  {
    id: '4',
    userId: '4',
    action: 'view',
    documentId: '1',
    timestamp: '2024-04-02T10:15:00Z',
  },
  {
    id: '5',
    userId: '1',
    action: 'download',
    documentId: '2',
    timestamp: '2024-04-03T11:20:00Z',
  },
  {
    id: '6',
    userId: '2',
    action: 'upload',
    documentId: '3',
    timestamp: '2024-04-10T11:20:00Z',
  },
  {
    id: '7',
    userId: '3',
    action: 'upload',
    documentId: '4',
    timestamp: '2024-04-15T16:45:00Z',
  },
  {
    id: '8',
    userId: '1',
    action: 'archive',
    documentId: '5',
    timestamp: '2024-04-20T13:00:00Z',
  },
  {
    id: '9',
    userId: '2',
    action: 'login',
    timestamp: '2024-04-20T09:30:00Z',
  },
  {
    id: '10',
    userId: '3',
    action: 'login',
    timestamp: '2024-04-20T09:45:00Z',
  },
  {
    id: '11',
    userId: '4',
    action: 'view',
    documentId: '3',
    timestamp: '2024-04-11T14:00:00Z',
  },
  {
    id: '12',
    userId: '1',
    action: 'download',
    documentId: '4',
    timestamp: '2024-04-16T10:00:00Z',
  },
  {
    id: '13',
    userId: '2',
    action: 'view',
    documentId: '2',
    timestamp: '2024-04-05T15:30:00Z',
  },
  {
    id: '14',
    userId: '3',
    action: 'upload',
    documentId: '6',
    timestamp: '2024-03-20T10:15:00Z',
  },
  {
    id: '15',
    userId: '4',
    action: 'download',
    documentId: '1',
    timestamp: '2024-04-19T16:45:00Z',
  },
]

export const mockCategories = ['Proposals', 'Permits', 'Budgets', 'Reports', 'Financial Records']
export const mockEvents = ['Freshmen Orientation', 'Election 2025', 'Foundation Day', 'General']
export const mockAdministrations = ['2024-2025', '2025-2026']
